package Model;

public class CellPhone extends Technology {

	/**
	 * Serial version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Number of sims to this phone
	 */
	private int numberOfSims;
	
	/**
	 * Number of camera for this phone
	 */
	private int numberOfCameras;
	
	/**
	* Its the constructor of CellPhone 
	* <br><b>Pre:<b> 
	* <br><b>Post:<b> All variables initializated
	* @param: name The cellphone name
	* @param: code The cellphone code autogenerated
	* @param: price The cellpone price to sale
	* @param: description The cellphone description
	* @param: picture The path of the picture for this phone
	* @param: quantity The actual quantity in stock of this cellphone
	* @param: bateryWatts The voltage of this cellphone
	* @param: screenSize The screen size
	* @param: ram Ram of the phone in GB
	* @param: processor Name of the processor phone
	* @param: numberOfSims Number of sims for this cellpone
	* @param:numberOfCameras Number of cameras for this cellphone
	**/
	public CellPhone(String name,String code,double price, String description, String picture, int quantity,double batteryWatts, double screenSize, int ram, String processor, int numberOfSims, int numberOfCameras) {
		super(name,code,price,description,picture,quantity,batteryWatts,screenSize,ram,processor);
		this.numberOfSims = numberOfSims;
		this.numberOfCameras = numberOfCameras;
	}

	/**
	* Allows to obtain the number of sims of the CellPhone
	* <br><b>Pre:<b> The CellPhone object must be created
	* <br><b>Post:<b> obtain the number of sims of the cell phone saved in variable "numberOfSims"
	* @return REturn the number of sims for this phone
	**/
	public int getNumberOfSims() {
		return numberOfSims;
	}

	/**
	* Allows entering a new number of sims for the CellPhone
	* <br><b>Pre:<b> The CellPhone object must be created
	* <br><b>Post:<b> the number of sims will be saved in the variable "numberOfSims"
	* @param numberOfSims The new number of sims to set
	**/
	public void setNumberOfSims(int numberOfSims) {
		this.numberOfSims = numberOfSims;
	}

	/**
	* Allows to obtain the number of cameras of the CellPhone
	* <br><b>Pre:<b> The CellPhone object must be created
	* <br><b>Post:<b> obtain the number of cameras of the cell phone saved in variable "numberOfCameras"
	* @return Return the number of cameras from this phone
	**/
	public int getNumberOfCameras() {
		return numberOfCameras;
	}

	/**
	* Allows entering a new number of cameras for the CellPhone
	* <br><b>Pre:<b> The CellPhone object must be created
	* <br><b>Post:<b> the number of cameras will be saved in the variable "numberOfCameras"
	* @param numberOfCameras The new number of cameras for this phone to set
	**/
	public void setNumberOfCameras(int numberOfCameras) {
		this.numberOfCameras = numberOfCameras;
	}
}
