package Model;

public class Computer extends Technology {

	/**
	 * Serial version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * If the computer is touch or not
	 */
	private boolean touch;
	
	/**
	 * The number of ports for this computer
	 */
	private int numberOfPorts;
	
	/**
	 * Constructor of computer class
	 * <br><b>Pre:<b> 
	 * <br><b>Post:<b> Attributes of computer has been initializated
	 * @param name the name of this computer
	 * @param code The computer code autogenerated
	 * @param price The computer pdice
	 * @param description The computer description to show
	 * @param picture The path of the picture for this computer
	 * @param quantity The actual quantity on sale of this computer
	 * @param batteryWatts The computer voltage
	 * @param screenSize The computare screen size in cm
	 * @param ram The computer ram in GB
	 * @param processor The name of the processor for this computer
	 * @param numberOfPorts The number of available ports
	 * @param touch If the computer is touch or not
	 */
	public Computer(String name,String code,double price, String description, String picture, int quantity,double batteryWatts, double screenSize, int ram, String processor, int numberOfPorts, boolean touch) {
		super(name,code,price,description,picture,quantity,batteryWatts,screenSize,ram,processor);
		this.touch = touch;
		this.numberOfPorts = numberOfPorts;
	}

	/**
	 * Getter of touch
	 * <br><b>Pre:<b> Variable touch must be initializated
	 * <br><b>Post:<b> 
	 * @return A boolean with the touch information
	 */
	public boolean getTouch() {
		return touch;
	}

	/**
	 * Setter of touch variable
	 * <br><b>Pre:<b> 
	 * <br><b>Post:<b> New touch has been setted
	 * @param touch The new tocuh
	 */
	public void setToch(boolean touch) {
		this.touch = touch;
	}
	
	/**
	 * Allows to obtain the String touch of the computer
	 * <br>Pre:<b>The Computer object must be created and touch must be entered</b>
	 * <br>Post:<b>obtain the smart String of the Computer saved in variable "answer"</b>
	 * @return answer;
	 */
	public String isTouchString() {
		String answer;
		answer = (touch)?"SI":"NO";
		return answer;
	}

	/**
	 * Getter of numberOfPorts
	 * <br><b>Pre:<b> Variable numberOfPorts must be initializated
	 * <br><b>Post:<b> 
	 * @return The number of ports
	 */
	public int getNumberOfPorts() {
		return numberOfPorts;
	}

	/**
	 * Setter of numberOfPorts
	 * <br><b>Pre:<b>  
	 * <br><b>Post:<b> A new number of ports has been setted
	 * @param numberOfPorts, the new number of ports
	 */
	public void setNumberOfPorts(int numberOfPorts) {
		this.numberOfPorts = numberOfPorts;
	}
	
}
