package Model;

public class HomeAppliances extends Article{

	/**
	 * Serial version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Weight of the article
	 */
	private double weight;
	
	/**
	 * Capacity of the article
	 */
	private double capacity;
	
	/**
	 * Electric consumption of the article
	 */
	private double wattsConsum;
	
	/**
	 * Height of the article
	 */
	private double height;
	
	/**
	 * Widht of the article
	 */
	private double width;
	
	/**
	* Its the constructor of HomeAppliaces.java 
	* <br><b>Pre:</b> 
	* <br><b>Post: All the variables will be initializated</b> 
	* @param: name The article name
	* @param: code The article code autogenerated
	* @param: price The article price
	* @param: description The article description
	* @param: picture Path of the article picture
	* @param: quantity Article quantity available to sell
	* @param: weight Weight of the article
	* @param: capacity Capacity of the article in Kg
	* @param: wattsConsum Electric consumption in watts
	* @param: height Height of the article
	* @param: width Article width
	**/
	public HomeAppliances(String name,String code,double price, String description, String picture, int quantity, double weight, double capacity, double wattsConsum, double height ,double widht) {
		super(name,code,price,description,picture,quantity);
		this.weight = weight;
		this.capacity = capacity;
		this.wattsConsum = wattsConsum;
		this.height = height;
		this.width = widht;
	}

	/**
	* Allows to obtain the weight of the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliances object must be created
	* <br><b>Post:</b> obtain the weight of the HomeAppliances saved in variable "weight"
	* @return Return the article weight
	**/
	public double getWeight() {
		return weight;
	}

	/**
	* Allows entering a new weight for the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliences object must be created
	* <br><b>Post:</b> the weight will be saved in the variable "weight"
	* @param weight Weight of the article
	**/
	public void setWeight(double weight) {
		this.weight = weight;
	}

	/**
	* Allows to obtain the capacity of the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliances object must be created
	* <br><b>Post:</b> obtain the capacity of the HomeAppliances saved in variable "capacity"
	* @return The capacitity of the article in kg
	**/
	public double getCapacity() {
		return capacity;
	}

	/**
	* Allows entering a new capacity for the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliences object must be created
	* <br><b>Post:</b> the capacity will be saved in the variable "capacity"
	* @param capacity The new capacity to set ini Kg
	**/
	public void setCapacity(double capacity) {
		this.capacity = capacity;
	}

	/**
	* Allows to obtain the wattsConsum of the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliances object must be created
	* <br><b>Post:</b> obtain the wattsConsum of the HomeAppliances saved in variable "wattsConsum"
	**/
	public double getWattsConsum() {
		return wattsConsum;
	}

	/**
	* Allows entering a new wattsConsum for the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliences object must be created
	* <br><b>Post:</b> the wattsConsum will be saved in the variable "wattsConsum"
	* @param wattsConsum New electric consumption to set
	**/
	public void setWattsConsum(double wattsConsum) {
		this.wattsConsum = wattsConsum;
	}

	/**
	* Allows to obtain the height of the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliances object must be created
	* <br><b>Post:</b> obtain the height of the HomeAppliances saved in variable "height"
	* @return Return the article height in Kg
	**/
	public double getHeight() {
		return height;
	}
	
	/**
	* Allows entering a new height for the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliences object must be created
	* <br><b>Post:</b> the height will be saved in the variable "height"
	* @param height The new height to set
	**/
	public void setHeight(double height) {
		this.height = height;
	}

	/**
	* Allows to obtain the width of the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliances object must be created
	* <br><b>Post:</b> obtain the width of the HomeAppliances saved in variable "width"
	* @return Return the width of the article in cm
	**/
	public double getWidth() {
		return width;
	}

	/**
	* Allows entering a new width for the HomeAppliances
	* <br><b>Pre:</b> The HomeAppliences object must be created
	* <br><b>Post:</b> the width will be saved in the variable "width"
	* @param: width The new width to set in cm
	**/
	public void setWidth(double width) {
		this.width = width;
	}

}
