package Model;

import java.util.Date;

public class Order {

	/**
	 * The date when the order started
	 */
	private Date date; 
	
	/**
	 * The order code autogenerated
	 */
	private int orderCode;
	
	/**
	 * The first node of the articles in this order
	 */
	private Article articles;
	
	/**
	* Its the constructor of Order 
	* <br><b>Pre:</b> 
	* <br><b>Post:</b> All variables will be initializated
	* @param date The date when the order started
	* @param codeOrder The order code autogenerated
	* @param articles The first node of the articles in this order
	**/
	public Order(int orderCode, Article articles) {
		this.date = new java.util.Date();
		this.orderCode = orderCode;
		this.articles = articles;
	}

	/**
	* Allows to obtain the date of the Order
	* <br><b>Pre:</b> The Order object must be created
	* <br><b>Post:</b> obtain the date of the Order saved in variable "date"
	* @return Return the date when the order started
	**/
	public Date getDate() {
		return date;
	}

	/**
	* Allows entering a new date for the Order
	* <br><b>Pre:</b> The Order object must be created
	* <br><b>Post:</b> the date will be saved in the variable "date"
	* @param date The new date when the order started to set
	**/
	public void setDate(Date date) {
		this.date = date;
	}
	
	/**
	* Allows to obtain the code order of the Order
	* <br><b>Pre:</b> The Order object must be created
	* <br><b>Post:</b> obtain the orderCode of the Order saved in variable "orderCode"
	* @return The order code autogenerated
	**/
	public int getOrderCode() {
		return orderCode;
	}

	/**
	* Allows entering a new order code  for the Order
	* <br><b>Pre:</b> The Order object must be created
	* <br><b>Post:</b> the order code will be saved in the variable "orderCode"
	* @param orderCode The new order code to set
	**/
	public void setOrderCode(int orderCode) {
		this.orderCode = orderCode;
	}

	/**
	* Allows to obtain the articles of the Order
	* <br><b>Pre:</b> The Order object must be created
	* <br><b>Post:</b> obtain the articles of the Order saved in variable "articles"
	* @return Return the articles first node in this order
	**/
	public Article getArticles() {
		return articles;
	}

	/**
	* Allows entering a new articles  for the Order
	* <br><b>Pre:</b> The Order object must be created
	* <br><b>Post:</b> the articles will be saved in the variable "articles"
	* @param articles The new first node of the articles in this order
	**/
	public void setArticles(Article articles) {
		this.articles = articles;
	}
	
	

}
