package Model;

public class Stove extends HomeAppliances{

	/**
	 * Serial version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * The numbe of Nozzles
	 */
	private int numberOfNozzles;
	
	/**
	 * The type of Stove in a String
	 */
	private String typeStove;
	
	/**
	* Its the constructor of Stove 
	* <br><b>Pre:</b> 
	* <br><b>Post: All variables will be initializated</b> 
	* @param: name The name of this Stove
	* @param: code The code of this stove autogenerated
	* @param: price The price of this stove
	* @param: description The description of this stove
	* @param: picture The path of the picture for this article
	* @param: quantity The quantity of this article available to sell
	* @param: weight The weight of this article in Kg
	* @param: capacity The capacity of this article in Kg
	* @param: wattsConsum The electric consumption in Watts
	* @param: height The height of this article in cm
	* @param: widht The widht of this article in cm
	* @param: numberOfNozzles The number of nozzles in this stove
	* @param: typeStove The type of Stove in a String
	**/
	public Stove(String name,String code,double price, String description, String picture, int quantity, double weight, double capacity, double wattsConsum, double height ,double widht, int numberOfNozzles, String typeStove) {
		super(name,code,price,description,picture,quantity,weight,capacity,wattsConsum,height,widht);
		this.numberOfNozzles = numberOfNozzles;
		this.typeStove = typeStove;
	}

	/**
	 * Allows to obtain the number of nozzles of the Stove
	 * <br>Pre:<b>The Stove object must be created</b>
	 * <br>Post:<b>obtain the number of nozzles of the Stove saved in variable "numberOfNozzles"</b>
	 * @return numberOfNozzles The number of nozzles
	 */
	public int getNumberOfNozzles() {
		return numberOfNozzles;
	}

	/**
	 * Allows entering a new number of nozzles for the Stove
	 * <br>Pre:<b>The Stove object must be created</b>
	 * <br>Post:<b>the number of nozzles will be saved in the variable "numberOfNozzles"</b>
	 * @param numberOfNozzles The new numbe of Nozzles to set
	 */
	public void setNumberOfNozzles(int numberOfNozzles) {
		this.numberOfNozzles = numberOfNozzles;
	}

	/**
	 * Allows to obtain the type of stove of the Stove
	 * <br>Pre:<b>The Stove object must be created</b>
	 * <br>Post:<b>obtain the type of stove of the Stove saved in variable "typeStove"</b>
	 * @return typeStove The type of Stove
	 */
	public String getTypeStove() {
		return typeStove;
	}

	/**
	 * Allows entering a new type stove for the Stove
	 * <br>Pre:<b>The Stove object must be created</b>
	 * <br>Post:<b>the type of stove will be saved in the variable "numberOfNozzles"</b>
	 * @param typeStove The new type of Stove to set
	 */
	public void setTypeStove(String typeStove) {
		this.typeStove = typeStove;
	}
}
