package Model;

public class Technology extends Article{

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * The battery of this article in Watts
	 */
	private double batteryWatts;
	
	/**
	 * The screen size in cm
	 */
	private double screenSize;
	
	/**
	 * The ram of this article in GB
	 */
	private int ram;
	
	/**
	 * The name of the processor in this article
	 */
	private String processor; 
	
	/**
	* Its the constructor of Technology 
	* <br><b>Pre:</b> 
	* <br><b>Post: All variables will be initializated</b> 
	* @param: name The article name
	* @param: code The article code autogenerated
	* @param: price The article price in double
	* @param: description The article description
	* @param: picture The path of the picture for this article
	* @param: quantity The quantity of this article available to sell
	* @param: bateryWatts The batery in Watts
	* @param: screenSize The screen Size in cm
	* @param: ram The available ram in GB
	* @param: processor The name fo the processor in this article
	**/
	public Technology(String name,String code,double price, String description, String picture, int quantity,double batteryWatts, double screenSize, int ram, String processor) {
		super(name,code,price,description,picture,quantity);
		this.batteryWatts = batteryWatts;
		this.screenSize = screenSize;
		this.ram = ram;
		this.processor = processor;
	}

	/**
	* Allows to obtain the batteryWatts of the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: obtain the watts to the batery of the technology saved in variable "batteryWatts"</b> 
	* @return The battery in watts
	**/
	public double getBatteryWatts() {
		return batteryWatts;
	}

	/**
	* Allows entering a new batteryWatts for the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: the watts of battery will be saved in the variable "batteryWatts"</b> 
	* @param batteryWatts Then new battery in watts to set
	**/
	public void setBatteryWatts(double batteryWatts) {
		this.batteryWatts = batteryWatts;
	}

	/**
	* Allows to obtain the size screen of the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: obtain the size to the screen of the technology saved in variable "screenTechnology"</b> 
	* @return The screen size in cm
	**/
	public double getScreenSize() {
		return screenSize;
	}

	/**
	* Allows entering a new size screen for the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: the screen size will be saved in the variable "screenSize"</b> 
	* @param: screenSize
	**/
	public void setScreenSize(double screenSize) {
		this.screenSize = screenSize;
	}

	/**
	* Allows to obtain the ram of the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: obtain the ram of the technology saved in variable "ram"</b> 
	* @return The available ram in GB
	**/
	public int getRam() {
		return ram;
	}

	/**
	* Allows entering a new ram for the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: the ram will be saved in the variable "ram"</b> 
	* @param ram The new ram available in gb to set
	**/
	public void setRam(int ram) {
		this.ram = ram;
	}

	/**
	* Allows to obtain the proccesor of the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: obtain the proccesor of the technology saved in variable "processor"</b>
	* @return The processor in a String
	**/
	public String getProcessor() {
		return processor;
	}

	/**
	* Allows entering a new processor for the technology
	* <br><b>Pre: The Technology object must be created</b> 
	* <br><b>Post: the processor will be saved in the variable "processor"</b> 
	* @param: processor The new processor name to set
	**/
	public void setProcessor(String processor) {
		this.processor = processor;
	}
}
